# Generated by Django 5.1.1 on 2024-10-25 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('seats', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fareapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehnum', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('licencep', models.FileField(upload_to='')),
                ('registrationp', models.FileField(upload_to='')),
                ('insurancep', models.FileField(upload_to='')),
                ('vehiclep', models.FileField(upload_to='')),
                ('qr', models.FileField(blank=True, null=True, upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fareapp.login_table')),
                ('VTYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fareapp.vehicletype')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fareapp.login_table'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('distance', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('bill', models.FileField(blank=True, null=True, upload_to='')),
                ('payment', models.CharField(default='pending', max_length=30)),
                ('CUSTOMER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fareapp.customer')),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fareapp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BigIntegerField()),
                ('review', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('TRIP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fareapp.trip')),
            ],
        ),
    ]
